import { Space_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/custom/Navbar/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const spaceMono = Space_Mono({ subsets: ["latin"], weight: "400" });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={spaceMono.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
